package oss

import (
	"context"
	"crypto/tls"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"runtime/pprof"

	"github.com/minio/mux"
	cli "github.com/urfave/cli/v3"
)

// tlsFlag 三态 HTTPS 开关：--tls 开启 / --no-tls 显式关闭 / 不传回退 env/rdb.conf/默认 HTTP。
var tlsFlag = &cli.BoolWithInverseFlag{
	BoolFlag: &cli.BoolFlag{
		Name:  "tls",
		Usage: "enable HTTPS (TLS) serving; default plain HTTP unless set via --no-tls/env/rdb.conf",
	},
}

var ServerFlags = []cli.Flag{
	&cli.StringFlag{
		Name:  "store",
		Value: STORE_ROOT_DIR,
		// EnvVars: []string{"AIO_OSS_STORE"},
	},
	&cli.StringFlag{
		Name:  "log-path",
		Value: LOG_DIR,
		// EnvVars: []string{"AIO_OSS_STORE"},
	},
	&cli.IntFlag{
		Name:  "port",
		Value: int64(PORT),
		// EnvVars: []string{"AIO_OSS_PORT"},
	},
	&cli.BoolFlag{
		Name:  "profile",
		Value: false,
	},
	&cli.BoolFlag{
		Name:  "profile-http",
		Value: false,
	},
	&cli.StringFlag{
		Name:  "config",
		Value: DEFAULT_RDB_CONFIG_PATH,
		Usage: "rdb.conf 配置文件路径（INI），提供 TLS/算法配置",
	},
	&cli.StringFlag{
		Name:  "cert-dir",
		Value: "",
		Usage: "证书目录，存放按算法前缀命名的证书材料",
	},
	&cli.StringFlag{
		Name:  "tls-algorithm",
		Value: "",
		Usage: "cert algorithm prefix: ed25519 (default, Go-loadable) / sm2 (GM, Go unsupported -> fail-closed); host cert must be generated first via 'tls-keygen ca/create/sign' as <prefix>_host.crt/<prefix>_host.key",
	},
	&cli.StringFlag{
		Name:  "cert-path",
		Value: "",
		Usage: "explicit server certificate (PEM); overrides prefix-based resolution; must be generated by tls-keygen",
	},
	&cli.StringFlag{
		Name:  "key-path",
		Value: "",
		Usage: "explicit server private key (PEM); overrides prefix-based resolution; must be generated by tls-keygen",
	},
	tlsFlag,
}

var serverCmd = &cli.Command{
	Name:   "server",
	Usage:  "start object storage server",
	Action: serverMain,
	Flags:  ServerFlags,
	OnUsageError: func(ctx context.Context, cmd *cli.Command, err error, isSubcommand bool) error {
		panic(err)
	},
}

func registerAPIRouter(router *mux.Router) {
	api := OssServer{}
	router.Methods(http.MethodHead).HandlerFunc(httpTrace(api.HeadHandler))
	router.Methods(http.MethodGet).HandlerFunc(httpTrace(api.GetHandler))
	router.Methods(http.MethodPut).HandlerFunc(httpTrace(api.PutHandler))
	router.Methods(http.MethodPost).HandlerFunc(httpTrace(api.PostHandler))
	router.Methods(http.MethodOptions).HandlerFunc(httpTrace(api.OptionsHandler))
	router.Methods(http.MethodDelete).HandlerFunc(httpTrace(api.DeleteHandler))
	router.NotFoundHandler = http.HandlerFunc(api.NotFoundHandler)
}

func serverMain(ctx context.Context, cmd *cli.Command) error {

	GConfig = NewConfig()
	GConfig.BuildConfig(cmd)
	GConfig.InitStoreRootDir()

	err := os.MkdirAll(GConfig.LogDir, 0755)
	if err != nil {
		panic(err)
	}
	f, err := os.OpenFile(GConfig.LogDir+"/"+GConfig.LogFileName, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		panic(err)
	}

	defer f.Close()

	log.SetOutput(f)

	log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile)

	log.Println("start server main")

	if GConfig.Profile {
		log.Println("start profile cpu")
		f, err := os.Create("cpu.pprof")
		if err != nil {
			panic(err)
		}
		pprof.StartCPUProfile(f)

		log.Println("start profile mem")
		f, err = os.Create("mem.pprof")
		if err != nil {
			panic(err)
		}
		pprof.WriteHeapProfile(f)

		log.Println("start profile goroutine")
		f, err = os.Create("goroutine.pprof")
		if err != nil {
			panic(err)
		}
		pprof.Lookup("goroutine").WriteTo(f, 2)
	}

	router := mux.NewRouter().SkipClean(true)
	registerAPIRouter(router)
	log.Printf("%+v\n", GConfig)

	if GConfig.ProfileHttp {
		go func() {
			httpProf := "0.0.0.0:6060"
			log.Printf("HTTP pprof listening at %q\n", httpProf)
			log.Println(http.ListenAndServe(httpProf, nil))
		}()
	}

	// HTTPS 开关解析：默认 HTTP；显式/配置开启后走 TLS 路径（证书缺失/非法 fail-closed 整体启动失败）
	GConfig.TLSEnabled = resolveTLSEnabled(GConfig)

	if GConfig.TLSEnabled {
		tlsCfg, certPath, keyPath, tlsErr := buildServingTLS(GConfig)
		if tlsErr != nil {
			fatalToStderr(describeTLSError(tlsErr, certPath, keyPath))
			return tlsErr
		}

		go func() {
			log.Printf("listening HTTPS on %q\n", fmt.Sprintf(":%d", GConfig.Port))
			if err := serveHTTPS(GConfig, router, tlsCfg, certPath, keyPath); err != nil {
				log.Println(err)
			}
		}()
	} else {
		go func() {
			log.Printf("listening HTTP on %q\n", fmt.Sprintf(":%d", GConfig.Port))
			if err := serveHTTP(GConfig, router); err != nil {
				log.Println(err)
			}
		}()
	}

	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)
	<-c

	if GConfig.Profile {
		pprof.StopCPUProfile()
	}
	return nil
}

// fatalToStderr 在致命启动错误时同时写入日志文件与控制台(stderr)，
// 避免启动失败被静默吞掉（仅进日志文件导致运维看到"启动异常"却无诊断）。
func fatalToStderr(msg string) {
	log.Print(msg)
	fmt.Fprintln(os.Stderr, msg)
}

// describeTLSError 把 TLS 启动失败格式化为可操作错误信息：包含失败原因、
// 期望的证书路径，以及用 tls-keygen 生成主机证书的方式（默认 ed25519，
// 可用 --tls-algorithm sm2 指定国密）。确保 fail-closed 时运维能直接在
// 控制台看到"缺哪个证书、怎么生成"，而非无提示退出。
func describeTLSError(tlsErr error, certPath, keyPath string) string {
	return fmt.Sprintf(
		"Error: failed to start TLS server: %v; generate the host certificate via 'tls-keygen ca/create/sign' (default algorithm ed25519, or --tls-algorithm sm2) -- looked for %s / %s",
		tlsErr, certPath, keyPath)
}

func serveHTTP(config *Config, handler http.Handler) error {
	addr := fmt.Sprintf(":%d", config.Port)
	srv := &http.Server{
		Addr:    addr,
		Handler: handler,
	}
	if err := srv.ListenAndServe(); err != nil {
		fatalToStderr(fmt.Sprintf("Error: failed to listen on %s: %v", addr, err))
		os.Exit(1)
	}
	return nil
}

func serveHTTPS(config *Config, handler http.Handler, tlsCfg *tls.Config, certPath, keyPath string) error {
	addr := fmt.Sprintf(":%d", config.Port)
	srv := &http.Server{
		Addr:      addr,
		Handler:   handler,
		TLSConfig: tlsCfg,
	}
	if err := srv.ListenAndServeTLS(certPath, keyPath); err != nil {
		fatalToStderr(fmt.Sprintf("Error: failed to listen on %s: %v", addr, err))
		os.Exit(1)
	}
	return nil
}
